In [1]:
import numpy as np

In [2]:
data= np.array(([1,2,3],[4,5,6]))

In [3]:
data * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [4]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('int64')

In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
np.empty((2,3,2))

array([[[  6.31719684e-310,   1.32324139e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [10]:
np.arange(34)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [11]:
array1 = np.array([1,2,3], dtype = np.float64)

In [12]:
array1.dtype

dtype('float64')

In [13]:
array1 = np.array([1,2,3], dtype = np.int32)

In [14]:
array1.dtype

dtype('int32')

In [15]:
array1.astype(np.float64)

array([ 1.,  2.,  3.])

In [16]:
array1 = np.array([1.12,2.35,3.98], dtype = np.float64)

In [17]:
array1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [18]:
arr = [[1,2,3], [4,5,6]]

In [19]:
arr = np.array(arr)

In [20]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [21]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
1/arr

array([[1, 0, 0],
       [0, 0, 0]])

In [23]:
0.5/arr

array([[ 0.5       ,  0.25      ,  0.16666667],
       [ 0.125     ,  0.1       ,  0.08333333]])

In [24]:
arr = np.arange(10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5]

5

In [27]:
arr[5:8]

array([5, 6, 7])

In [28]:
arr[5:8] = 12

In [29]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [30]:
arr_slice = arr[5:8]

In [31]:
arr_slice

array([12, 12, 12])

In [32]:
arr_slice[1] = 12345

In [33]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [34]:
names = np.array(['B', 'J', 'W', 'S', 'T', 'U', 'B'])

In [35]:
names

array(['B', 'J', 'W', 'S', 'T', 'U', 'B'],
      dtype='|S1')

In [36]:
data = np.random.randn(7,4)

In [37]:
data

array([[-0.14710724,  1.63474737,  0.51369989,  1.27236461],
       [-0.93724507, -1.15955395,  0.21459858, -0.04813333],
       [-0.54037781, -0.24186459, -0.06234561,  0.40590237],
       [-0.12390578, -0.00593123,  1.46478565,  0.43409455],
       [-0.91826529, -1.17709541,  0.65162262,  0.76056129],
       [ 0.07025681,  0.25778634, -1.68977661,  1.94108804],
       [-3.38518714, -1.04302401, -1.47873537, -0.19012862]])

In [38]:
names == 'B'

array([ True, False, False, False, False, False,  True], dtype=bool)

In [39]:
data[names == 'B']

array([[-0.14710724,  1.63474737,  0.51369989,  1.27236461],
       [-3.38518714, -1.04302401, -1.47873537, -0.19012862]])

In [40]:
data[names == 'B', :2]

array([[-0.14710724,  1.63474737],
       [-3.38518714, -1.04302401]])

In [41]:
data[names == 'B',3]

array([ 1.27236461, -0.19012862])

In [42]:
data[names != 'B']

array([[-0.93724507, -1.15955395,  0.21459858, -0.04813333],
       [-0.54037781, -0.24186459, -0.06234561,  0.40590237],
       [-0.12390578, -0.00593123,  1.46478565,  0.43409455],
       [-0.91826529, -1.17709541,  0.65162262,  0.76056129],
       [ 0.07025681,  0.25778634, -1.68977661,  1.94108804]])

In [43]:
data[(names == 'B') | (names == 'T')]

array([[-0.14710724,  1.63474737,  0.51369989,  1.27236461],
       [-0.91826529, -1.17709541,  0.65162262,  0.76056129],
       [-3.38518714, -1.04302401, -1.47873537, -0.19012862]])

In [44]:
data[data<0] = 0

In [45]:
data

array([[ 0.        ,  1.63474737,  0.51369989,  1.27236461],
       [ 0.        ,  0.        ,  0.21459858,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.40590237],
       [ 0.        ,  0.        ,  1.46478565,  0.43409455],
       [ 0.        ,  0.        ,  0.65162262,  0.76056129],
       [ 0.07025681,  0.25778634,  0.        ,  1.94108804],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [46]:
data[(names == 'B') | (names == 'T')] = 11

In [47]:
data

array([[ 11.        ,  11.        ,  11.        ,  11.        ],
       [  0.        ,   0.        ,   0.21459858,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.40590237],
       [  0.        ,   0.        ,   1.46478565,   0.43409455],
       [ 11.        ,  11.        ,  11.        ,  11.        ],
       [  0.07025681,   0.25778634,   0.        ,   1.94108804],
       [ 11.        ,  11.        ,  11.        ,  11.        ]])

In [48]:
arr = np.empty((8,4))

In [49]:
arr

array([[  6.31719684e-310,   1.33674638e-316,   0.00000000e+000,
          0.00000000e+000],
       [  8.27578358e-313,   2.14027814e+161,   5.04621383e+180,
          4.50618615e-144],
       [  7.79952704e-143,   4.50605602e-144,   4.27255699e+180,
          2.91237123e+257],
       [  5.56111702e+180,   2.16385138e+190,   3.29983050e-033,
          2.17564513e-076],
       [  2.09501180e-076,   4.28684352e-033,   4.27406296e-096,
          9.08366793e+223],
       [  1.28906334e+030,   5.82134975e-057,   3.32709717e-076,
          2.51961299e-071],
       [  1.41529402e+161,   9.16651763e-072,   4.31383994e+097,
          2.11183003e-052],
       [  7.43672294e-144,   8.27578359e-313,   6.31718147e-310,
          1.63041663e-322]])

In [50]:
for i in range(8):
    arr[i] = i

In [51]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [52]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [53]:
arr[[4]]

array([[ 4.,  4.,  4.,  4.]])

In [54]:
arr[[-4,-5,-1]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 7.,  7.,  7.,  7.]])

In [55]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [56]:
arr.reshape((4,8))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.]])

In [57]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [58]:
ar = np.arange(32).reshape(8,4)

In [59]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
ar[[1,4,5,7],[0, 1,2,3]]

array([ 4, 17, 22, 31])